development:
  adapter: postgresql
  encoding: unicode
  database: cupcake_app_development
  host: localhost
  username: alexdavidow
  pool: 5

# test: &test
test:
  adapter: postgresql
  encoding: unicode
  database: cupcake_app_test
  host: localhost
  username: alexdavidow
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cupcake_app_production
  host: localhost
  username: alexdavidow
  pool: 5

# cucumber:
#   <<: *test